### ISSUE TITLE
Great library, thanks!

### ISSUE THREAD

**Issue by AdrianMrn** [keriwarr/splitwise#14]
At [spatie](https://github.com/spatie), We're now automatically adding our lunch order to our Splitwise group. Thanks to your repo, the Splitwise implementation was super easy! The documentation is comprehensive & extensive, thanks a bunch!

Maybe add an example of a `createExpense` POST request to the docs? The one in Splitwise's API docs isn't completely clear either. I had to check the network tab of my Chrome dev tools while adding an expense to check what the form data had to look like.

Maybe I'll send a PR next week to add this myself :)

**Comment by keriwarr** [comment]
Thanks for the feedback <3 I will look in to it when I get some time
