### ISSUE TITLE
[Object] in repayments and users

### ISSUE THREAD

**Issue by efurban** [keriwarr/splitwise#2]
Not sure what but receives the following return with [Object] in it, when calling sw.getExpenses({ group_id: group_id })
could you give me a pointer? thanks. 

`[ { id: 383272047,
    group_id: 1484568,
    friendship_id: null,
    expense_bundle_id: null,
    description: 'HBO Now',
    repeats: true,
    repeat_interval: 'monthly',
    email_reminder: false,
    email_reminder_in_advance: -1,
    next_repeat: '2018-06-20T04:00:00Z',
    details: null,
    comments_count: 0,
    payment: false,
    creation_method: 'equal',
    transaction_method: 'offline',
    transaction_confirmed: false,
    transaction_id: null,
    cost: '16.32',
    currency_code: 'USD',
    repayments:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    date: '2018-05-20T04:00:00Z',
    created_at: '2018-05-20T04:32:15Z',
    created_by:
     { id: 41211,
       first_name: 'Travis',
       last_name: 'Wu',
       picture: [Object] },
    updated_at: '2018-05-20T04:32:15Z',
    updated_by:
     { id: 41211,
       first_name: 'Travis',
       last_name: 'Wu',
       picture: [Object] },
    deleted_at: null,
    deleted_by: null,
    category: { id: 18, name: 'General' },
    receipt: { large: null, original: null },
    users:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] } ]
`

**Comment by keriwarr** [comment]
Sorry, I was accidentally not watching this repo T_T

**Comment by keriwarr** [comment]
can I close this? @efurban

**Comment by efurban** [comment]
Yes. You can. I’ve achieved what I needed. Thanks.
