### ISSUE TITLE
only enables access to a single user's content

### ISSUE THREAD

**Issue by goleary** [keriwarr/splitwise#22]
I'm trying to build a web app that makes use of Splitwise's API to be able to create debts for users of my app.
It appears as though using a client secret is required, so I can't use their API from my client side application.  I'm implementing a server layer to do the communication with Splitwise's API for this reason and their website points to this library.

I'm attempting to use firebase functions for my server layer as such:
![image](https://user-images.githubusercontent.com/16123225/68816789-5a396b80-0634-11ea-86ef-7080f6cf44c5.png)

Whenever I hit this endpoint I get data from my account returned even though at no point was i shown an authorization screen. This is the case no matter which device I hit my endpoint from.

Is it the case that this library only provides access to the developers data? and that I can't enable users to access their own data through this library?

**Comment by keriwarr** [comment]
> Is it the case that this library only provides access to the developers data?
 
@goleary I'm sorry to say that that is the case. I didn't get around to implementing all the oauth grant types. You will need to access the API directly for that purpose.

**Comment by goleary** [comment]
good to know.  It would be awesome if info to that effect was included in the readme.  I spent quite a bit of time messing with this library only to realize it wouldn't meet my needs.  Kind of surprised the splitwise docs give this lib a shout out given its limitations. I can submit a PR with this clarification if you're cool with it.

**Comment by keriwarr** [comment]
sure.

2019年11月14日(木) 0:47 goleary <notifications@github.com>:
