### ISSUE TITLE
Unknown authentication errors when trying this library

### ISSUE THREAD

**Issue by pjatx** [keriwarr/splitwise#27]
**Describe the bug**
I'm getting authentication errors when trying a very simple usage of this library. 

**To Reproduce**
1. Create and register a new application
1. Install this library. 
1. Configure per the instructions
1. Make any API call

**Expected behavior**
Expected to see user object returned

**Actual behavior**
Error: authentication failed - unknown error

**Snippets/stack-traces**

**Environment (please complete the following information):**
 - Node version: [e.g. 8.12.0]

**Additional context**

Current Usage
```
const sw = Splitwise({
  consumerKey: {my_consumer_key},
  consumerSecret: {my_consumer_secret},
  logger: console.log
})

sw.getCurrentUser()
  .then(user => console.log(user))
  .catch(err => console.log(err))
```

**Comment by keriwarr** [comment]
Sorry, I can't reproduce the issue @pjatx. The example you provided works for me. Let me know if you have more any more details about how to reproduce.

**Comment by pjatx** [comment]
I was able to get this fixed - thanks!

**Comment by Nsrose** [comment]
How did you fix this?
