### ISSUE TITLE
How to upload receipt image via sw.createExpense?

### ISSUE THREAD

**Issue by demobo-com** [keriwarr/splitwise#3]
How to upload receipt image via sw.createExpense?
There is no documentation for this.

**Comment by keriwarr** [comment]
Sorry, I was accidentally not watching this repo. Can I close the issue? @demobo-com

**Comment by keriwarr** [comment]
http://dev.splitwise.com/dokuwiki/doku.php?id=create_expense

**Comment by demobo-com** [comment]
@keriwarr is the answer No? I can not find an image upload solution in the documentation.

**Comment by keriwarr** [comment]
@demobo-com just so you know I don't represent or maintain the splitwise api, but you're right, it's not in the docs.

If I create an expense using splitwise.com I see that they upload the image via an undocumented field called `receipt`.

In this case, the `Content-Type` of the request was set to `multipart/form-data; boundary=----WebKitFormBoundaryXXXXXXXXX` and the image was uploaded with it's own Content-Type as binary data. I suspect that if you tried to use this field as is with my library it wouldn't work, but I'm not sure. I think you can expect that my library won't support this for a while (unless you make a PR for it :) ) but thanks for bringing this up, I'll definitely put it on my to-do list.
