### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by demobo-com** [keriwarr/splitwise#4]
Getting the following error:
(node:9992) UnhandledPromiseRejectionWarning: Error: authentication failed - client error

oauth2.getOAuthAccessToken('',
  { grant_type: 'client_credentials' },
  (_, token) => console.log(token)
);

Now, this will result { statusCode: 400, data: '{"error":"unsupported_grant_type"}' }

**Comment by chocomega** [comment]
It also stopped working for me a few days ago  with the same error.

I don't know if it's related but on the [API doc](https://dev.beta.splitwise.com/?javascript--oauth2#authentication) the grant type is **'authorization_code'** instead of **'client_credentials'**:

```    /** Obtaining access_token */
    client.getOAuthAccessToken(
      qsObj.code,
      {
        'redirect_uri': MY_CALLBACK_URL,
        'grant_type': 'authorization_code'
      },
      function(e, access_token, refresh_token, results) {
        if (e) {
          console.log(e);
          res.end(JSON.stringify(e));
        } else if (results.error) {
          console.log(results);
          res.end(JSON.stringify(results));
        }
        else {
          console.log('Obtained access_token: ', access_token);
          client.get('https://secure.splitwise.com/api/v3.0/get_current_user', access_token, function(e, data, response) {
            if (e) console.error(e);
            res.end(data);
          });
        }
      });
```
It is possible that they "disabled" 'client_credentials' grant type ?

**Comment by franomai** [comment]
Hi there. I am working on a workaround for this and I'll share it if I'm successful. I have also messaged the splitwise developers about this issue, but I do not know if/when they will reply.

I am actually new to this project, so I was just wondering - when you authenticate as you did in the previous way, who was the user you were logged in as? When you performed an action, how did it register?

EDIT: Looks grim, even if you mock the the authorization you still have to log in, and the login has a captcha >.>' Maybe someone else should send an email?

**Comment by demobo-com** [comment]
I think client_credentials is no longer supported by splitwise.
My workaround for now is using oAuth interface to get the accessToken and instantiate Splitwise using the accessToken.

`
const sw = Splitwise({
  consumerKey: 'Ae..........',
  consumerSecret: 'e7.........',
  accessToken: 'aKD........'
})
`

**Comment by franomai** [comment]
I was going to type a response here about fetching the accessToken and if that can expire, but then I fired up the non-working code and suddenly I can auth. Is it working for anyone else? Maybe they re-enabled it?

**Comment by rohanprabhu** [comment]
@franomai Can confirm, was facing the same issue and now it is working

**Comment by jhottenstein** [comment]
Hello!

I'm one of the Splitwise developers and I can confirm that client_credentials grant type was not working and we have since fixed it.  Sorry for the inconvenience.

If you have problems in the future, please don't hesitate to reach out to developers@splitwise.com.

**Comment by keriwarr** [comment]
Thanks @jhottenstein !
